In [1]:
import numpy as np
import pandas as pd

In [2]:
species = ['falcon', 'dog', 'spider', 'fish']
feature_1 = [2, 4, 8, 0]
feature_2 = [2, 0, 0, 0]

animals = pd.DataFrame({"num_legs": feature_1, "num_specimen_seen": feature_2}, index=species)
print('Type of variable animals is ', type(animals))
print('Type of a column from DataFrame animals is ', type(animals["num_specimen_seen"]))
animals

Type of variable animals is  <class 'pandas.core.frame.DataFrame'>
Type of a column from DataFrame animals is  <class 'pandas.core.series.Series'>


num_legs  num_specimen_seen
falcon         2                  2
dog            4                  0
spider         8                  0
fish           0                  0

In [3]:
feature_3 = [2, 0, 0, 0]
animals["num_wings"] = feature_3
animals

num_legs  num_specimen_seen  num_wings
falcon         2                  2          2
dog            4                  0          0
spider         8                  0          0
fish           0                  0          0

In [4]:
X = animals[["num_legs", "num_wings"]]
X

num_legs  num_wings
falcon         2          2
dog            4          0
spider         8          0
fish           0          0

In [5]:
X_np = X.values
print(type(X_np))

<class 'numpy.ndarray'>


In [6]:
X_np

array([[2, 2],
       [4, 0],
       [8, 0],
       [0, 0]], dtype=int64)

In [7]:
X_np.shape

(4, 2)

In [8]:
a = np.array([2, 4, 8, 0])
print(a, type(a))

[2 4 8 0] <class 'numpy.ndarray'>


In [9]:
b = np.ones(shape=(1, 4))
print(b, type(b))

[[1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [10]:
c = np.zeros(shape=(5, 4))
print(c, type(c))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>


In [11]:
d = np.zeros_like(X_np)
print(d, type(d))

[[0 0]
 [0 0]
 [0 0]
 [0 0]] <class 'numpy.ndarray'>


In [12]:
print(a.reshape(2, 2))

[[2 4]
 [8 0]]


In [13]:
print(a.reshape(2, -1)) # -1 means "count it for me"

[[2 4]
 [8 0]]


In [14]:
e = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(e.T) # .T means transpose

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [15]:
print("Transposing converts an object of shape", e.shape, "into an object of shape", e.T.shape, ".")

Transposing converts an object of shape (2, 4) into an object of shape (4, 2) .


In [16]:
print("X_np\n", X_np)
print("d\n", d)
print("result\n", np.concatenate([X_np, d], axis=1))

X_np
 [[2 2]
 [4 0]
 [8 0]
 [0 0]]
d
 [[0 0]
 [0 0]
 [0 0]
 [0 0]]
result
 [[2 2 0 0]
 [4 0 0 0]
 [8 0 0 0]
 [0 0 0 0]]


In [17]:
print("result\n", np.concatenate([X_np, d], axis=0)) # depending on the specified axis

result
 [[2 2]
 [4 0]
 [8 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [18]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1, "+", v2, "=", v1 + v2)
print(v1, "-", v2, "=", v1 - v2)

[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]


In [19]:
print("<", v1, ", ", v2.T, ".T> =", v1.dot(v2.T))

< [1 2 3] ,  [4 5 6] .T> = 32


In [20]:
print(v1, "*", v2, "=", v1 * v2)

[1 2 3] * [4 5 6] = [ 4 10 18]


In [21]:
print(v1, "^2 =", v1**2)

[1 2 3] ^2 = [1 4 9]


In [22]:
print(v1, "* 2 =", v1 * 2)

[1 2 3] * 2 = [2 4 6]
